"""initial tables

Revision ID: 99cb7de05b76
Revises: 
Create Date: 2026-07-07 06:18:45.095621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cb7de05b76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('protected_attributes', sa.JSON(), nullable=True),
    sa.Column('detected_proxies', sa.JSON(), nullable=True),
    sa.Column('target_column', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dataset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('baseline_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'profiling', 'running_metrics', 'mitigating', 'generating_report', 'completed', 'failed', name='auditstatus'), nullable=False),
    sa.Column('agent_trace', sa.JSON(), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('audit_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('protected_attribute', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ci_lower', sa.Float(), nullable=True),
    sa.Column('ci_upper', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitigation_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('audit_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('stage_type', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('fairness_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mitigation_results')
    op.drop_table('metric_results')
    op.drop_table('audit_runs')
    op.drop_table('models')
    op.drop_table('datasets')
    # ### end Alembic commands ###
